// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI_denvI55x5R-Cj1keGij6hPfEje84NI',
    appId: '1:594185581418:web:ecd7ddbbbb3850cff9ab13',
    messagingSenderId: '594185581418',
    projectId: 'flutter-tutorial-194a1',
    authDomain: 'flutter-tutorial-194a1.firebaseapp.com',
    storageBucket: 'flutter-tutorial-194a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo6GABZdN3ImmnBnUu4-TjiNbNBfxssBs',
    appId: '1:594185581418:android:43bc6f294dbce531f9ab13',
    messagingSenderId: '594185581418',
    projectId: 'flutter-tutorial-194a1',
    storageBucket: 'flutter-tutorial-194a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtbBMOJngasCkUoE7il7PSmlyxIUsq7Cw',
    appId: '1:594185581418:ios:f4c253144b43ff6af9ab13',
    messagingSenderId: '594185581418',
    projectId: 'flutter-tutorial-194a1',
    storageBucket: 'flutter-tutorial-194a1.appspot.com',
    iosClientId: '594185581418-r826elev5porfufe3eb2mj0b7rful1h0.apps.googleusercontent.com',
    iosBundleId: 'com.example.keijiban',
  );
}
